apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana
  namespace: grafana
spec:
  config:
    security:
      admin_password: admin
      admin_user: admin
  dataStorage:
    accessModes:
      - ReadWriteOnce
    class: gp2
    volumeName: grafana-pvc
