apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  labels:
    app: kafka-cluster
  generation: 1
  namespace: amq-streams
spec:
  kafka:
    template:
          pod:
            tolerations:
              - key: "reserved"
                operator: "Equal"
                value: "amqstreams"
                effect: "NoSchedule"
    config:
      offsets.topic.replication.factor: 2
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: '3.3'
      log.message.format.version: '3.3'
      log.retention.hours: 48
      auto.create.topics.enable: false
    metricsConfig:
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml
      type: jmxPrometheusExporter
    resources:
      limits:
        memory: 2G
        cpu: '0.5'
      requests:
        cpu: '0.5'
        memory: 1G
    authorization:
      superUsers:
        - admin
      type: simple
    storage:
      volumes:
        - deleteClaim: false
          id: 0
          size: 50Gi
          type: persistent-claim
        - deleteClaim: false
          id: 1
          size: 30Gi
          type: persistent-claim
      type: jbod
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - authentication:
          type: scram-sha-512
        name: tls
        port: 9093
        type: internal
        tls: true
      - authentication:
          type: scram-sha-512
        name: external
        port: 9094
        type: route
        tls: true
    replicas: 3
    version: 3.3.1
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"  
  entityOperator:
    topicOperator: {}
    userOperator:
      secretPrefix: user-
  zookeeper:
    metricsConfig:
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: zookeeper-metrics-config.yml
      type: jmxPrometheusExporter
    storage:
      deleteClaim: false
      size: 20Gi
      type: persistent-claim
    replicas: 3
