# Setting up the monitoring stack
## 1 - Enabling user-workload-monitoring
If the cluster-monitoring-config already exists, you just need to update it
```shell
oc -n openshift-monitoring edit configmap cluster-monitoring-config
```
If it doesn't exist, you must create it.
```shell
cat <<EOF |oc apply -f -  
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    enableUserWorkload: true
EOF
```
## 2 - You can create a grafana namespace or use the same of amq-streams and you can install using the operator or deployment, below you have the both options
*In this case we are using a new namespace that was called grafana.*
Using the operator
== Creating the PVC
```shell
oc apply -f kuberesources/grafana-pvc.yaml
```
== Creating grafana
```shell
oc apply -f kuberesources/grafana.yaml
```
= Grating the cluster-monitoring-view cluster role to grafana-serviceaccount.
```shell
oc adm policy add-cluster-role-to-user cluster-monitoring-view -z grafana-serviceaccount
```
== Using the bearer token to authenticate access to Prometheus.
```shell
BEARER_TOKEN=$(oc serviceaccounts get-token grafana-serviceaccount -n grafana)
```
== Creating Grafana Data Source.
#Replace the ${BEARER_TOKEN} with the extracted in the step 4.
```yaml
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: prometheus-grafanadatasource
  namespace: grafana
spec:
  datasources:
    - access: proxy
      editable: true
      isDefault: true
      jsonData:
        httpHeaderName1: 'Authorization'
        timeInterval: 5s
        tlsSkipVerify: true
      name: Prometheus
      secureJsonData:
        httpHeaderValue1: 'Bearer ${BEARER_TOKEN}'
      type: prometheus
      url: 'https://thanos-querier.openshift-monitoring.svc.cluster.local:9091'
  name: prometheus-grafanadatasource.yaml
```
== Creating the PodMonitor.
```yaml
  namespaceSelector:
    matchNames:
      - <REPLACE_WITH_NAMESPACE_NAME>
```
```shell
oc apply kuberesources/pod-monitor.yaml
```
== Import the dashboard into grafana, you only need to copy content from files kuberesources/strimzi-dashboard and import through the grafana interface.
